version: "3.8"
services:
  llm-api:
    image: local/llm-api:latest
    ports:
      - "13000:8000"

  neo4j:
    image: neo4j:5.22.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/12345678"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
    restart: unless-stopped

  graph-rag-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: 12345678
    depends_on:
      - neo4j
      - llm-api

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - graph-rag-agent
